"""create initial tables

Revision ID: 8f61a83e90b4
Revises: 
Create Date: 2026-08-11 19:19:23.990046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f61a83e90b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_packages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('expected_response_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_packages_is_active', 'reading_packages', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_logs_action_code', 'action_logs', ['action_code'], unique=False)
    op.create_index('ix_action_logs_actor_id_created_at', 'action_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_action_logs_target_type_target_id', 'action_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('reader_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'assigned', 'completed', 'canceled', 'refunded', 'in_progress', 'disputing', name='booking_status'), server_default='pending', nullable=False),
    sa.Column('package_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('price_snapshot', sa.Integer(), nullable=False),
    sa.Column('expected_response_minutes_snapshot', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['reading_packages.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_customer_id_status', 'bookings', ['customer_id', 'status'], unique=False)
    op.create_index('ix_bookings_reader_id_status', 'bookings', ['reader_id', 'status'], unique=False)
    op.create_index('ix_bookings_status_created_at', 'bookings', ['status', 'created_at'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('reason_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewing', 'resolved', 'rejected', name='dispute_status'), server_default='open', nullable=False),
    sa.Column('verdict', sa.Enum('refund_full', 'refund_partial', 'rejected', name='dispute_verdict'), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('refund_amount IS NULL OR refund_amount >= 0', name='ck_disputes_refund_amount_non_negative'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_disputes_admin_id_status', 'disputes', ['admin_id', 'status'], unique=False)
    op.create_index('ix_disputes_status_created_at', 'disputes', ['status', 'created_at'], unique=False)
    op.create_table('service_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_messages_booking_id_created_at', 'service_messages', ['booking_id', 'created_at'], unique=False)
    op.create_index('ix_service_messages_sender_id', 'service_messages', ['sender_id'], unique=False)
    op.create_table('dispute_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('comment', 'evidence', 'system', name='dispute_message_type'), server_default=sa.text("'comment'::dispute_message_type"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_messages_dispute_id_created_at', 'dispute_messages', ['dispute_id', 'created_at'], unique=False)
    op.create_index('ix_dispute_messages_sender_id', 'dispute_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dispute_messages_sender_id', table_name='dispute_messages')
    op.drop_index('ix_dispute_messages_dispute_id_created_at', table_name='dispute_messages')
    op.drop_table('dispute_messages')
    op.drop_index('ix_service_messages_sender_id', table_name='service_messages')
    op.drop_index('ix_service_messages_booking_id_created_at', table_name='service_messages')
    op.drop_table('service_messages')
    op.drop_index('ix_disputes_status_created_at', table_name='disputes')
    op.drop_index('ix_disputes_admin_id_status', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_bookings_status_created_at', table_name='bookings')
    op.drop_index('ix_bookings_reader_id_status', table_name='bookings')
    op.drop_index('ix_bookings_customer_id_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_action_logs_target_type_target_id', table_name='action_logs')
    op.drop_index('ix_action_logs_actor_id_created_at', table_name='action_logs')
    op.drop_index('ix_action_logs_action_code', table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index('ix_users_role_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_reading_packages_is_active', table_name='reading_packages')
    op.drop_table('reading_packages')
    # ### end Alembic commands ###
